import Link from 'next/link'
import { Activity, Users, AlertTriangle, TrendingUp, Shield, Database } from 'lucide-react'

export default function HomePage() {
  return (
    <div className="max-w-7xl mx-auto px-4 py-12">
      {/* Hero */}
      <div className="text-center mb-16">
        <div className="inline-flex items-center gap-2 bg-teal-50 text-teal-700 px-4 py-2 rounded-full text-sm font-medium mb-6 border border-teal-200">
          <Shield className="w-4 h-4" />
          Academic Demonstration System
        </div>
        <h1 className="text-5xl font-bold text-gray-900 mb-4">
          ICU Risk Prediction
          <span className="text-teal-600"> System</span>
        </h1>
        <p className="text-xl text-gray-600 max-w-2xl mx-auto mb-8">
          Temporal risk monitoring for ICU patients using hour-by-hour vital sign and lab data analysis.
          Built on MIMIC-III data structure.
        </p>
        <div className="flex gap-4 justify-center">
          <Link href="/dashboard" className="btn-primary inline-flex items-center gap-2 text-lg px-6 py-3">
            <Users className="w-5 h-5" />
            View Patients
          </Link>
          <a
            href="http://localhost:8000/docs"
            target="_blank"
            rel="noopener noreferrer"
            className="btn-secondary inline-flex items-center gap-2 text-lg px-6 py-3"
          >
            <Database className="w-5 h-5" />
            API Docs
          </a>
        </div>
      </div>

      {/* Warning Banner */}
      <div className="bg-amber-50 border border-amber-200 rounded-xl p-6 mb-12 flex gap-4">
        <AlertTriangle className="w-6 h-6 text-amber-500 flex-shrink-0 mt-0.5" />
        <div>
          <p className="font-semibold text-amber-800">Academic Demonstration Only</p>
          <p className="text-amber-700 text-sm mt-1">
            Risk scores are generated by simple rule-based logic and are NOT clinically validated.
            This system should never be used to make clinical decisions. Patient data shown is synthetic.
          </p>
        </div>
      </div>

      {/* Feature Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-12">
        <div className="card hover:shadow-md transition-shadow">
          <div className="w-12 h-12 bg-teal-100 rounded-xl flex items-center justify-center mb-4">
            <Activity className="w-6 h-6 text-teal-600" />
          </div>
          <h3 className="text-lg font-semibold text-gray-900 mb-2">Hourly Monitoring</h3>
          <p className="text-gray-600 text-sm">
            Track vital signs, lab values, and clinical events on an hour-by-hour basis throughout the ICU stay.
          </p>
        </div>

        <div className="card hover:shadow-md transition-shadow">
          <div className="w-12 h-12 bg-orange-100 rounded-xl flex items-center justify-center mb-4">
            <TrendingUp className="w-6 h-6 text-orange-500" />
          </div>
          <h3 className="text-lg font-semibold text-gray-900 mb-2">Risk Scoring</h3>
          <p className="text-gray-600 text-sm">
            Rule-based risk classification into Low, Medium, and High categories based on physiological thresholds.
          </p>
        </div>

        <div className="card hover:shadow-md transition-shadow">
          <div className="w-12 h-12 bg-red-100 rounded-xl flex items-center justify-center mb-4">
            <AlertTriangle className="w-6 h-6 text-red-500" />
          </div>
          <h3 className="text-lg font-semibold text-gray-900 mb-2">Alert Generation</h3>
          <p className="text-gray-600 text-sm">
            Automatic alerts when patient risk level escalates, with specific triggers and clinical context.
          </p>
        </div>
      </div>

      {/* Data Schema Info */}
      <div className="card">
        <h2 className="text-xl font-semibold text-gray-900 mb-4">Data Sources</h2>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {[
            { file: 'patients.csv', desc: 'Demographics' },
            { file: 'admissions.csv', desc: 'Hospital admissions' },
            { file: 'icustays.csv', desc: 'ICU stay periods' },
            { file: 'chartevents.csv', desc: 'Vital sign readings' },
            { file: 'labevents.csv', desc: 'Lab test results' },
            { file: 'prescriptions.csv', desc: 'Medications' },
            { file: 'procedures.csv', desc: 'Clinical procedures' },
            { file: 'd_labitems.csv', desc: 'Lab item definitions' },
          ].map(({ file, desc }) => (
            <div key={file} className="bg-gray-50 rounded-lg p-3">
              <p className="text-xs font-mono text-teal-600 font-medium">{file}</p>
              <p className="text-xs text-gray-500 mt-1">{desc}</p>
            </div>
          ))}
        </div>
        <p className="text-sm text-gray-500 mt-4">
          Place MIMIC-III CSV files in <code className="bg-gray-100 px-1 py-0.5 rounded text-xs">backend/data/</code> to use real data.
          Sample data with synthetic ICU scenarios is provided by default.
        </p>
      </div>
    </div>
  )
}
